spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.i4a65zg.mongodb.net/NewJournalDB?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=NewJournalDB
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG